/**
 * writeFoundation.js
 * Agent 4 script — Reads Style Dictionary output and writes/updates Kotlin
 * Compose foundation files in the Android project's foundations/ folder.
 *
 * Rules:
 *   - If a .kt file doesn't exist → creates it from the template below.
 *   - If it exists → replaces only the content between
 *       // <figma-ds:generated ...>  and  // </figma-ds:generated>
 *     Code outside those markers is preserved.
 *   - Calls saveVersion.js on successful completion.
 */

import 'dotenv/config';
import fs from 'fs-extra';
import path from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '../..');

const BUILD_DIR       = path.join(ROOT, 'tokens', 'build', 'android');
const FOUNDATIONS_DIR = path.resolve(
  ROOT,
  'AndroidApp/FigmaDS/app/src/main/java/com/gajendrakarn/figmadsapp/foundations'
);
const PACKAGE = 'com.gajendrakarn.figmadsapp.foundations';

const OPEN_MARKER  = '// <figma-ds:generated';
const CLOSE_MARKER = '// </figma-ds:generated>';

function tick(step, message) {
  console.log(`[✓] ${step} ${message}`);
}

// ─── Category → Kotlin file spec ─────────────────────────────────────────────
const CATEGORY_SPECS = {
  colors: {
    file: 'Colors.kt',
    objectName: 'FigmaColors',
    imports: ['androidx.compose.ui.graphics.Color'],
    renderToken: (name, token) => `    val ${toPascalCase(name)} = ${token.value}`,
  },
  typography: {
    file: 'Typography.kt',
    objectName: 'FigmaTypography',
    imports: [
      'androidx.compose.ui.text.TextStyle',
      'androidx.compose.ui.text.font.Font',
      'androidx.compose.ui.text.font.FontFamily',
      'androidx.compose.ui.text.font.FontWeight',
      'androidx.compose.ui.unit.sp',
    ],
    renderToken: (name, token) => `    val ${toPascalCase(name)} = ${token.value}`,
  },
  dimensions: {
    file: 'Dimensions.kt',
    objectName: 'FigmaDimensions',
    imports: [
      'androidx.compose.ui.unit.Dp',
      'androidx.compose.ui.unit.dp',
    ],
    renderToken: (name, token) => `    val ${toPascalCase(name)}: Dp = ${token.value}`,
  },
  borders: {
    file: 'Borders.kt',
    objectName: 'FigmaBorders',
    imports: ['androidx.compose.ui.unit.dp'],
    renderToken: (name, token) => `    val ${toPascalCase(name)} = ${token.value}`,
  },
  elevation: {
    file: 'Elevation.kt',
    objectName: 'FigmaElevation',
    imports: ['androidx.compose.ui.unit.dp'],
    renderToken: (name, token) => {
      // Elevation from Figma effect: value may be an array of effects or a single string
      const rendered = Array.isArray(token.value)
        ? `${renderElevationEffect(token.value)}`
        : `${token.value}`;
      return `    val ${toPascalCase(name)} = ${rendered}`;
    },
  },
  opacity: {
    file: 'Opacity.kt',
    objectName: 'FigmaOpacity',
    imports: [],
    renderToken: (name, token) => `    val ${toPascalCase(name)} = ${token.value}`,
  },
};

function renderElevationEffect(effects) {
  // For now, pick first drop shadow and output as Dp elevation
  const shadow = Array.isArray(effects) ? effects.find(e => e.type === 'DROP_SHADOW') : null;
  if (shadow) {
    const radius = Math.round(shadow.radius ?? 0);
    return `${radius}.dp`;
  }
  return '0.dp';
}

// ─── Helpers ──────────────────────────────────────────────────────────────────
function toPascalCase(str) {
  return str
    .replace(/[_\-\s]+(.)/g, (_, c) => c.toUpperCase())
    .replace(/^(.)/, c => c.toUpperCase())
    .replace(/[^a-zA-Z0-9]/g, '');
}

function buildGeneratedBlock(spec, tokens, version) {
  const timestamp = new Date().toISOString();
  const tokenEntries = Object.entries(tokens);

  const lines = [];
  lines.push(`${OPEN_MARKER} version="${version}" updated="${timestamp}">`);
  lines.push(`object ${spec.objectName} {`);

  if (tokenEntries.length === 0) {
    lines.push('    // No tokens found for this category');
  } else {
    for (const [name, token] of tokenEntries) {
      if (token.description) {
        lines.push(`    /** ${token.description} */`);
      }
      lines.push(spec.renderToken(name, token));
    }
  }

  lines.push('}');
  lines.push(CLOSE_MARKER);
  return lines.join('\n');
}

function buildFullFile(spec, generatedBlock) {
  const importLines = spec.imports.map(i => `import ${i}`).join('\n');
  return [
    `package ${PACKAGE}`,
    '',
    importLines,
    '',
    '// AUTO-GENERATED by FigmaDS agent. Do not edit the generated block manually.',
    generatedBlock,
    '',
  ].join('\n');
}

function replaceGeneratedBlock(existingContent, newBlock) {
  const openIdx = existingContent.indexOf(OPEN_MARKER);
  const closeIdx = existingContent.indexOf(CLOSE_MARKER);

  if (openIdx === -1 || closeIdx === -1) {
    // Markers not found — append the block at the end
    return existingContent.trimEnd() + '\n\n' + newBlock + '\n';
  }

  return (
    existingContent.slice(0, openIdx) +
    newBlock +
    existingContent.slice(closeIdx + CLOSE_MARKER.length)
  );
}

// ─── Main ─────────────────────────────────────────────────────────────────────
async function main() {
  console.log('\n[foundation-sync] Writing Android foundation files...');

  // Read current pending version (set by checkVersion.js)
  const pendingPath = path.join(ROOT, '.version-pending.json');
  let version = 'unknown';
  if (await fs.pathExists(pendingPath)) {
    const pending = await fs.readJson(pendingPath);
    version = pending.pendingVersion ?? 'unknown';
  }

  await fs.ensureDir(FOUNDATIONS_DIR);

  const builtFiles = (await fs.readdir(BUILD_DIR).catch(() => [])).filter(f => f.endsWith('.json'));

  if (builtFiles.length === 0) {
    throw new Error(`No built token files found in ${BUILD_DIR}. Run build.js first.`);
  }

  let created = 0, updated = 0;

  for (const jsonFile of builtFiles) {
    const category = path.basename(jsonFile, '.json'); // e.g. "colors"
    const spec = CATEGORY_SPECS[category];

    if (!spec) {
      console.log(`  [!] Unknown category "${category}" — skipping`);
      continue;
    }

    const tokens = await fs.readJson(path.join(BUILD_DIR, jsonFile)).catch(() => ({}));
    const ktPath = path.join(FOUNDATIONS_DIR, spec.file);
    const generatedBlock = buildGeneratedBlock(spec, tokens, version);

    let action;
    if (await fs.pathExists(ktPath)) {
      const existing = await fs.readFile(ktPath, 'utf-8');
      const updated_content = replaceGeneratedBlock(existing, generatedBlock);
      await fs.writeFile(ktPath, updated_content, 'utf-8');
      action = 'updated';
      updated++;
    } else {
      const fullFile = buildFullFile(spec, generatedBlock);
      await fs.writeFile(ktPath, fullFile, 'utf-8');
      action = 'created';
      created++;
    }

    tick(`${category}`, `${spec.file} ${action} (${Object.keys(tokens).length} tokens)`);
  }

  // Persist the version now that sync succeeded
  try {
    execSync('node scripts/figma/saveVersion.js', { cwd: ROOT, stdio: 'inherit' });
  } catch {
    console.warn('[foundation-sync] Warning: saveVersion.js failed — version cache not updated');
  }

  console.log(`\n[foundation-sync] ✅ Done — ${created} created, ${updated} updated\n`);
}

main().catch(err => {
  console.error(`\n[foundation-sync] ❌ Fatal: ${err.message}`);
  if (process.env.DEBUG) console.error(err.stack);
  process.exit(1);
});
