package com.gajendrakarn.figmadsapp.foundations

import androidx.compose.ui.unit.dp

// AUTO-GENERATED by FigmaDS agent. Do not edit the generated block manually.
// <figma-ds:generated version="2352349693565067465" updated="2026-05-11T15:08:36.080Z">
object FigmaElevation {
    val Shadow = 40.dp
}
// </figma-ds:generated>
