package com.gajendrakarn.figmadsapp.foundations

import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.Font
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.sp

// AUTO-GENERATED by FigmaDS agent. Do not edit the generated block manually.
// <figma-ds:generated version="2352349693565067465" updated="2026-05-11T15:08:36.081Z">
object FigmaTypography {
    val Body = TextStyle(
        fontFamily = FontFamily(Font("Poppins")),
        fontWeight = FontWeight.Normal,
        fontSize = 14.sp,
        lineHeight = 21.0.sp
    )
    val SectionInnerTitle = TextStyle(
        fontFamily = FontFamily(Font("Poppins")),
        fontWeight = FontWeight.SemiBold,
        fontSize = 16.sp,
        lineHeight = 20.8.sp
    )
    val SectionTitle = TextStyle(
        fontFamily = FontFamily(Font("Poppins")),
        fontWeight = FontWeight.SemiBold,
        fontSize = 24.sp,
        lineHeight = 31.2.sp
    )
    val OneLinerRegular = TextStyle(
        fontFamily = FontFamily(Font("Poppins")),
        fontWeight = FontWeight.Normal,
        fontSize = 14.sp,
        lineHeight = 16.0.sp
    )
    val ScreenTitle = TextStyle(
        fontFamily = FontFamily(Font("Poppins")),
        fontWeight = FontWeight.SemiBold,
        fontSize = 36.sp,
        lineHeight = 46.8.sp
    )
    val SmallRegular = TextStyle(
        fontFamily = FontFamily(Font("Poppins")),
        fontWeight = FontWeight.Normal,
        fontSize = 12.sp,
        lineHeight = 15.6.sp
    )
    val OneLinerSemiBold = TextStyle(
        fontFamily = FontFamily(Font("Poppins")),
        fontWeight = FontWeight.SemiBold,
        fontSize = 14.sp,
        lineHeight = 16.0.sp
    )
    val SmallSemiBold = TextStyle(
        fontFamily = FontFamily(Font("Poppins")),
        fontWeight = FontWeight.SemiBold,
        fontSize = 12.sp,
        lineHeight = 15.6.sp
    )
    val ExtraSmallSemiBold = TextStyle(
        fontFamily = FontFamily(Font("Poppins")),
        fontWeight = FontWeight.SemiBold,
        fontSize = 10.sp,
        lineHeight = 10.0.sp
    )
}
// </figma-ds:generated>
